
# gpu_id: 1
seed: 42
### Roots
train_root: "/root/autodl-tmp/clas_experiments/RandStainNA-master/classification/100K-NONORM-png/train0"
test_root: "/root/autodl-tmp/clas_experiments/RandStainNA-master/classification/100K-NONORM-png/test"
output_path: "/root/autodl-tmp/clas_experiments/staintrick/results/" 
postfix: 'LabNorm_7_densenet121'
### Model & Schemes
model: "densenet121" # model_name in Timm
# requires_grad: False 
pretrained: False # If to use the ImageNet pretrained weights
prenorm: True # If to use the prenorm scheme
emaprenorm: False # If to use the EMA variant of prenorm scheme
emaprenorm_lambda: 0.01
randnorm: False # If to use the randnorm scheme
temnorm: False 
# hsvnorm: True 
# hednorm: False 
### Training Configurations
num_workers: 15
batch_size: 128
learning_rate: 5.0e-4
weight_decay: 1.0e-5
min_learning_rate: 5.0e-6
T_max: 10
gamma: 0.8
epochs: 100
patience: 8
scheduler: 'cosine' 
scheduler_norm: "step" # 学习层不同的scheduler
mu0: [61.2880, 31.9137, -7.8419]
sigma0: [12.6320,  8.7228,  6.0945] 

mu0_hsv: [5.1988, 0.2328, 0.8036]
sigma0_hsv: [0.5707, 0.1016, 0.1033]
mu0_lab: [70.5085,  21.9641, -13.7990]
sigma0_lab: [12.7103,  8.7185,  6.0168]